# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - Dev - VM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
      # Debug: Echo to print the contents of the build directory
      - name: Debug - Print the contents of the build directory
        run: |
          echo "Contents of the build output directory:"
          dir "${{env.DOTNET_ROOT}}\\myapp" # List the contents of the publish directory
  Dev:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C2FEE75B84E4A6C8AF7FB179F4C9BEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B489BE8A568B486B9E17D00599EEF12D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3DDA30F4C843470996401A54C943C70C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AzureLearningDotNet'
          slot-name: 'Production'
          package: .

  VM:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'VM'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Write SSH private key to file
        run: |
          # Write the SSH private key to a temporary file
          echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}"
          echo "AAAAB3NzaC1yc2EAAAADAQABAAABgQC32xQ1A4n/Ormpg9uE/Zz1FnP9rKQVnVREgfDJxZqZHklGCRlTS77nm1WyNCcpl0q37mrYq+08O/3LBDl9efGE+U1LPr4jca9OB6WK0XLXEBmZXEG7+JZEo/R9PmI0NO+nGh3xRd6mb/IMFXt4mDTvoxHilN87G4dH8e4JlfurNqL0sAl+0wltrN99Yfa9t8Cw80EgZzyVUIilGwG8dOWNdF6GXSojAwp43WFGedUCxiWNNZKav1+SfXTugP7CUxhCYZvRBCfLz3Ae3JRiujKGv3GqPWXwYnt+ynmrBQqStn50iZtVTuHull2gkVTQBFJcB8Ags6ffSwaMExnlL6vSbEfKCfMjDtkZv5YhPw+Rz+TUzavngHRP9yGA8Lxwn5FQPdbqGGLj1TMOs9O21gP4tvC+5szfPkFi2svivuwhC19+3ox1lydoDrgSis4pfv6r4N6pfSY5di50UbW7JlQd73g6T848CxKC913VZTFK7l0p5+VS6GmOfVCnie3xMz0=" > private_key.pem
          chmod 600 private_key.pem  # Make sure the file has proper permissions

      #- name: Copy files to Azure VM
      #  run: |
      #    # Define variables
      #    $VM_IP: 172.174.226.164
      #    $VM_USER: azureuser
      #    # Copy the files from the GitHub runner to the Azure VM using SSH private key
      #    scp -o StrictHostKeyChecking=no -i "MIIG5AIBAAKCAYEAt9sUNQOJ/zq5qYPbhP2c9RZz/aykFZ1URIHwycWamR5JRgkZU0u+55tVsjQnKZdKt+5q2KvtPDv9ywQ5fXnxhPlNSz6+I3GvTgelitFy1xAZmVxBu/iWRKP0fT5iNDTvpxod8UXepm/yDBV7eJg076MR4pTfOxuHR/HuCZX7qzai9LAJftMJbazffWH2vbfAsPNBIGc8lVCIpRsBvHTljXRehl0qIwMKeN1hRnnVAsYljTWSmr9fkn107oD+wlMYQmGb0QQny89wHtyUYroyhr9xqj1l8GJ7fsp5qwUKkrZ+dImbVU7h7pZdoJFU0ARSXAfAILOn30sGjBMZ5S+r0mxHygnzIw7ZGb+WIT8Pkc/k1M2r54B0T/chgPC8cJ+RUD3W6hhi49UzDrPTttYD+LbwvubM3z5BYtrL4r7sIQtfft6MdZcnaA64EorOKX7+q+DeqX0mOXYudFG1uyZUHe94Ok/OPAsSgvdd1WUxSu5dKeflUuhpjn1Qp4nt8TM9AgMBAAECggGATJ1gqE7XPKKOJ9OosJy2wXMf1sAQiGlNalbzrkFIETKLukGkag+QeBdE+MO+5hgDrO4PXEcYzxb4xZb3FhCw0obI7Ogyd7ayJMQO+fAZ+QDeigfl5JzMkcH46hALAFJm462AeMBy7cyMgviYwUI8HPhJRbBf7dOk5hgs55W2kDxuX6TT8COlNCzr3OXr2lcuVw6nPweGOXqb1qGQcaYM2ot5sGg2XOyxenhWRvYSC9viXhvLAe1puDPLfHAIuZXCOqvjQnQpFrl4/miKHv+/AO02og90dXii+HfHsesCcjY+xX2SScVQMMl93S4UY2ky1gPtdI+1xFsUd7q7VqLl7u0642lVxP2O5f1T7J9jkF6jIcfPziHSXQBjM8QctinLt0ogwpk3uUDzfVgC6shwtiRROWofTX88Iz4aO1S39pBM/AuxOUwOuqzuE7/xRvb5GlYb1nynVD0iJB8SgJ4Jn/FkMbFYsmZUeApEg27EEhEeRjP3dNQqfYXeP/On2RKJAoHBAMZLi1BlIVzwntJpK5+3kD01O9UscBt3KorNzczjGJ6XXEpdPuejhgp7gWO1TfJW5RasjC7dsZM8dKDqIAMZegPSumcXacjH9rj00il2qo7jSkAp09rNUHJhGiPibGVGHqkbbhnVFRzaRPZ0dx+M/Jjz3rX00hrrtNogEOsqD4A6YGE212ib05BIqb2ovEW08Ms2HObjxqVsUSSmIL9cKndBe3ybHIDIJ/fo5cjP9/TQlKfCwqYjevx6d2yPafjDiwKBwQDtW9gWXVZiP3b0XBUFInx8ToDBRJFfb471zGnI7B32NwJCNGMb1t9sjcJI28mCat7CGKwYG5G713GqObn/Mx3vpCCzNErdDGlFqXhqQ0PsiZ7etBCJeCLro8mlBBwEUHM5T9DgEUNeLJX1fnH+T1n9YhNjJYdvPYR31eHHunnybDaMsQNQKVpXaUkGN65ZhcY/w0b5znf170uhNh8oN3p0M4ajmDZ8hZzGMtpiOq1bsSfiZL/njABiM3t0vbzAHVcCgcEAk7rKQo3lSjF1kXqK5oXCLueO+OUPbFbeWeSzkxYJTHWlaz2G1NntzbdvkRIMzSPRro/ELFI7rl6W4R8r1ENRtLF078Lwq4XWGLtEK2Hd9W/97El9LQBTE7Ol3uAcM2MHCqOF5jbqcMFoKVhhOx81PNpKrLKFKUs7RFopYJnITJaxIRvTZXraJh8MXmDsSt5fmnVpGNbPMoS8+xnNQeNvO8OMNSv2EzeLF1Xqgy31I+2VIlql21KJmLnAaR97Krq7AoHBAOFZWm3ZTeNXV8umBPrsA/5M1ecn/1D5bGQnH6P3sHaLQWSzsgjDVzoL2JItwUJFzpm+rNzyh8ksQakYx2LoGBrl23noQs9dMjFGNaHFnR5chm3vzOeHHLhVt2Mo5KSf8NVP1wJ0wV4OvIzn8Lg+hDSRwdBW2B+f6z2O3Z4viAnF/YBTqs6XhEMLHZ5+jNRHsrHk52TSRohDGa3D4Y7gJS1fogt9vvU4MWDm9Plftikgp7pEZwIhpFeXgzWR0jsfXwKBwDniPOwt7CqgHIzH4/ZWXcy8f37jbZEp/7hVdOmxbnYy9+6bY+5wcjOokixSYrcqCPfclQqq+f35wUAd8GPttbUT1JyEL05kgmj/TIsIeS9KDIfYshslAuaicUA5Ln0AoZA3yRAqhg0BBGo8WQsWMs1stSVBSNftd8NrdwGILGK2e34ApOZ4O3Nkf51RoPEZFow4lTuzEWOPtJw4Sj6mthkXIFlnA/s5f0BQ+4FW0QOvviUOzYP4tLiOM9j/PvzyMw==" -r C:\Program Files\dotnet\myapp azureuser@172.174.226.164:/home/azureuser/myapp

      - name: Copy files to Azure VM
        with: 
          # Define variables
          $VM_IP: 172.174.226.164
          $VM_USER: azureuser
          script:
            # Copy the files from the GitHub runner to the Azure VM using SSH private key
            scp -o StrictHostKeyChecking=no -i "MIIG5AIBAAKCAYEAt9sUNQOJ/zq5qYPbhP2c9RZz/aykFZ1URIHwycWamR5JRgkZU0u+55tVsjQnKZdKt+5q2KvtPDv9ywQ5fXnxhPlNSz6+I3GvTgelitFy1xAZmVxBu/iWRKP0fT5iNDTvpxod8UXepm/yDBV7eJg076MR4pTfOxuHR/HuCZX7qzai9LAJftMJbazffWH2vbfAsPNBIGc8lVCIpRsBvHTljXRehl0qIwMKeN1hRnnVAsYljTWSmr9fkn107oD+wlMYQmGb0QQny89wHtyUYroyhr9xqj1l8GJ7fsp5qwUKkrZ+dImbVU7h7pZdoJFU0ARSXAfAILOn30sGjBMZ5S+r0mxHygnzIw7ZGb+WIT8Pkc/k1M2r54B0T/chgPC8cJ+RUD3W6hhi49UzDrPTttYD+LbwvubM3z5BYtrL4r7sIQtfft6MdZcnaA64EorOKX7+q+DeqX0mOXYudFG1uyZUHe94Ok/OPAsSgvdd1WUxSu5dKeflUuhpjn1Qp4nt8TM9AgMBAAECggGATJ1gqE7XPKKOJ9OosJy2wXMf1sAQiGlNalbzrkFIETKLukGkag+QeBdE+MO+5hgDrO4PXEcYzxb4xZb3FhCw0obI7Ogyd7ayJMQO+fAZ+QDeigfl5JzMkcH46hALAFJm462AeMBy7cyMgviYwUI8HPhJRbBf7dOk5hgs55W2kDxuX6TT8COlNCzr3OXr2lcuVw6nPweGOXqb1qGQcaYM2ot5sGg2XOyxenhWRvYSC9viXhvLAe1puDPLfHAIuZXCOqvjQnQpFrl4/miKHv+/AO02og90dXii+HfHsesCcjY+xX2SScVQMMl93S4UY2ky1gPtdI+1xFsUd7q7VqLl7u0642lVxP2O5f1T7J9jkF6jIcfPziHSXQBjM8QctinLt0ogwpk3uUDzfVgC6shwtiRROWofTX88Iz4aO1S39pBM/AuxOUwOuqzuE7/xRvb5GlYb1nynVD0iJB8SgJ4Jn/FkMbFYsmZUeApEg27EEhEeRjP3dNQqfYXeP/On2RKJAoHBAMZLi1BlIVzwntJpK5+3kD01O9UscBt3KorNzczjGJ6XXEpdPuejhgp7gWO1TfJW5RasjC7dsZM8dKDqIAMZegPSumcXacjH9rj00il2qo7jSkAp09rNUHJhGiPibGVGHqkbbhnVFRzaRPZ0dx+M/Jjz3rX00hrrtNogEOsqD4A6YGE212ib05BIqb2ovEW08Ms2HObjxqVsUSSmIL9cKndBe3ybHIDIJ/fo5cjP9/TQlKfCwqYjevx6d2yPafjDiwKBwQDtW9gWXVZiP3b0XBUFInx8ToDBRJFfb471zGnI7B32NwJCNGMb1t9sjcJI28mCat7CGKwYG5G713GqObn/Mx3vpCCzNErdDGlFqXhqQ0PsiZ7etBCJeCLro8mlBBwEUHM5T9DgEUNeLJX1fnH+T1n9YhNjJYdvPYR31eHHunnybDaMsQNQKVpXaUkGN65ZhcY/w0b5znf170uhNh8oN3p0M4ajmDZ8hZzGMtpiOq1bsSfiZL/njABiM3t0vbzAHVcCgcEAk7rKQo3lSjF1kXqK5oXCLueO+OUPbFbeWeSzkxYJTHWlaz2G1NntzbdvkRIMzSPRro/ELFI7rl6W4R8r1ENRtLF078Lwq4XWGLtEK2Hd9W/97El9LQBTE7Ol3uAcM2MHCqOF5jbqcMFoKVhhOx81PNpKrLKFKUs7RFopYJnITJaxIRvTZXraJh8MXmDsSt5fmnVpGNbPMoS8+xnNQeNvO8OMNSv2EzeLF1Xqgy31I+2VIlql21KJmLnAaR97Krq7AoHBAOFZWm3ZTeNXV8umBPrsA/5M1ecn/1D5bGQnH6P3sHaLQWSzsgjDVzoL2JItwUJFzpm+rNzyh8ksQakYx2LoGBrl23noQs9dMjFGNaHFnR5chm3vzOeHHLhVt2Mo5KSf8NVP1wJ0wV4OvIzn8Lg+hDSRwdBW2B+f6z2O3Z4viAnF/YBTqs6XhEMLHZ5+jNRHsrHk52TSRohDGa3D4Y7gJS1fogt9vvU4MWDm9Plftikgp7pEZwIhpFeXgzWR0jsfXwKBwDniPOwt7CqgHIzH4/ZWXcy8f37jbZEp/7hVdOmxbnYy9+6bY+5wcjOokixSYrcqCPfclQqq+f35wUAd8GPttbUT1JyEL05kgmj/TIsIeS9KDIfYshslAuaicUA5Ln0AoZA3yRAqhg0BBGo8WQsWMs1stSVBSNftd8NrdwGILGK2e34ApOZ4O3Nkf51RoPEZFow4lTuzEWOPtJw4Sj6mthkXIFlnA/s5f0BQ+4FW0QOvviUOzYP4tLiOM9j/PvzyMw==" -r C:\Program Files\dotnet\myapp azureuser@172.174.226.164:/home/azureuser/myapp

      - name: SSH into Azure VM and restart app
        run: |
          $VM_IP=172.174.226.164
          $VM_USER=azureuser

          # SSH into the Azure VM and restart the app or service
          ssh -o StrictHostKeyChecking=no -i private_key.pem azureuser@172.174.226.164 <<EOF
            # Navigate to the app directory
            cd /home/azureuser/myapp

            # If you're using systemd, restart the service
            sudo systemctl restart myapp.service  # Ensure that the service is defined on the VM

            # Or run the app directly (if not using a service manager)
            # nohup dotnet myapp.dll &
          EOF  
